image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node LTS x64
  - cmd: npm install

build_script:
  - cmd: npm run build
  - cmd: npx electron-builder -w

artifacts:
  - path: dist\Nowallet*.exe

test: off
