image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node LTS x64
  - cmd: npm install

build_script:
  - sh: >-
    npm run build
    npx electron-builder -w

test: off
